/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** System */
        get: operations["system_api_system_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BinaryStatus */
        BinaryStatus: {
            /** Path */
            path?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "missing" | "error" | "unknown";
            /** Version */
            version?: string | null;
        };
        /** GpuInfo */
        GpuInfo: {
            /** Driver Version */
            driver_version: string;
            /** Index */
            index: number;
            /** Memory Free Mb */
            memory_free_mb: number;
            /** Memory Total Mb */
            memory_total_mb: number;
            /** Memory Used Mb */
            memory_used_mb: number;
            /** Name */
            name: string;
        };
        /** GpuStatus */
        GpuStatus: {
            /** Detail */
            detail?: string | null;
            /**
             * Devices
             * @default []
             */
            devices: components["schemas"]["GpuInfo"][];
            /**
             * Source
             * @default nvidia-smi
             * @constant
             */
            source: "nvidia-smi";
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "missing" | "error" | "unknown";
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /** Version */
            version: string;
        };
        /** PrivacyStatus */
        PrivacyStatus: {
            /** Offline Mode */
            offline_mode: boolean;
            /** Telemetry Enabled */
            telemetry_enabled: boolean;
        };
        /** StorageStatus */
        StorageStatus: {
            /** Data Dir */
            data_dir: string;
            /** Free Gb */
            free_gb: number;
            /** Total Gb */
            total_gb: number;
            /** Used Gb */
            used_gb: number;
        };
        /** SystemResponse */
        SystemResponse: {
            /** App Env */
            app_env: string;
            /** App Name */
            app_name: string;
            /** Device Preference */
            device_preference: string;
            /** Fake Providers Enabled */
            fake_providers_enabled: boolean;
            ffmpeg: components["schemas"]["BinaryStatus"];
            ffprobe: components["schemas"]["BinaryStatus"];
            gpu: components["schemas"]["GpuStatus"];
            /** Performance Profile */
            performance_profile: string;
            /** Platform */
            platform: string;
            privacy: components["schemas"]["PrivacyStatus"];
            /** Python Version */
            python_version: string;
            storage: components["schemas"]["StorageStatus"];
            /** Version */
            version: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    system_api_system_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemResponse"];
                };
            };
        };
    };
}
